version: '3.4'

services:
  sdc:
    container_name: dockersdc-server
    restart: always
    image: sdc
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3002:3002
    volumes:
      - .:/usr/src/app
    links:
      - mongodb
  mongodb:
    container_name: dockersdc-mongo
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - data:/data/db

volumes:
  data:
